%top{
#define YYSTYPE int
#include "codex.tab.h"         /* Token values generated by bison */
}
%option noyywrap
%%
/*Definir os tokens necessarios */
[01]         { return BIT; }    /* Single character literal into token */
\n                              /* munch */
%%


